const $=s=>document.querySelector(s),app=$('#app'),content=$('#content');let a={},limits={},outfits=[],tab='identity';const post=(n,b={})=>fetch(`https://${GetParentResourceName()}/${n}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(b)}).then(r=>r.json());
const face=['Orr szélesség','Orr magasság','Orr hossz','Orrhíd','Orrcsúcs','Orr csavarás','Szemöldök magasság','Szemöldök előre','Arccsont magasság','Arccsont szélesség','Arc szélesség','Szem nyitottság','Ajak vastagság','Állkapocs szélesség','Állkapocs forma','Áll magasság','Áll hossz','Áll szélesség','Áll bemélyedés','Nyak vastagság'];
const comps=[2,3,4,6,8,11,1,5,7,9,10],props=[0,1,2,6,7];
function rng(label,kind,id,field,val,min,max,step=.01){return `<div class="control"><label>${label}</label><input type="range" min="${min}" max="${max}" step="${step}" value="${val??0}" data-kind="${kind}" data-id="${id}" data-field="${field}"><output>${val??0}</output></div>`}
function render(){document.querySelectorAll('.tabs button').forEach(b=>b.classList.toggle('on',b.dataset.tab===tab));let h='';
if(tab==='identity'){h=`<div class="section"><h3>Karaktermodell</h3><div class="model"><button data-model="male" class="${a.model!=='mp_f_freemode_01'?'on':''}">Férfi</button><button data-model="female" class="${a.model==='mp_f_freemode_01'?'on':''}">Nő</button></div></div><div class="section"><h3>Származás</h3>${rng('Arc 1','blend',0,'shapeFirst',a.headBlend?.shapeFirst,0,45,1)}${rng('Arc 2','blend',0,'shapeSecond',a.headBlend?.shapeSecond,0,45,1)}${rng('Bőr 1','blend',0,'skinFirst',a.headBlend?.skinFirst,0,45,1)}${rng('Bőr 2','blend',0,'skinSecond',a.headBlend?.skinSecond,0,45,1)}${rng('Arc keverés','blend',0,'shapeMix',a.headBlend?.shapeMix,0,1,.01)}${rng('Bőr keverés','blend',0,'skinMix',a.headBlend?.skinMix,0,1,.01)}</div><div class="section"><h3>Arcforma</h3>${face.map((x,i)=>rng(x,'face',i,'value',a.faceFeatures?.[i]??a.faceFeatures?.[String(i)]??0,-1,1,.01)).join('')}</div><div class="section"><h3>Arcrészletek</h3>${Object.entries(limits.overlays||{}).map(([i,n])=>rng(n,'overlay',i,'index',a.overlays?.[i]?.index||0,0,20,1)+rng(n+' erősség','overlay',i,'opacity',a.overlays?.[i]?.opacity||0,0,1,.01)+rng(n+' szín','overlay',i,'color',a.overlays?.[i]?.color||0,0,63,1)).join('')}</div>`}
if(tab==='hair'){let l=limits.components?.['2']||{};h=`<div class="section"><h3>Haj</h3>${rng('Frizura','component',2,'drawable',a.components?.['2']?.drawable||0,0,Math.max(0,(l.drawables||1)-1),1)}${rng('Textúra','component',2,'texture',a.components?.['2']?.texture||0,0,20,1)}${rng('Hajszín','hair',0,'color',a.hair?.color||0,0,63,1)}${rng('Melír','hair',0,'highlight',a.hair?.highlight||0,0,63,1)}</div>`}
if(tab==='clothes')h=comps.filter(i=>i!==2).map(i=>{let l=limits.components?.[String(i)]||{},v=a.components?.[String(i)]||{};return `<div class="section"><h3>${l.label||'Komponens '+i}</h3>${rng('Fazon','component',i,'drawable',v.drawable||0,0,Math.max(0,(l.drawables||1)-1),1)}${rng('Textúra','component',i,'texture',v.texture||0,0,Math.max(0,((l.textures||{})[String(v.drawable)]||1)-1),1)}</div>`}).join('');
if(tab==='props')h=props.map(i=>{let l=limits.props?.[String(i)]||{},v=a.props?.[String(i)]||{drawable:-1,texture:0};return `<div class="section"><h3>Kiegészítő ${i}</h3>${rng('Fazon','prop',i,'drawable',v.drawable??-1,-1,Math.max(-1,(l.drawables||0)-1),1)}${rng('Textúra','prop',i,'texture',v.texture||0,0,20,1)}</div>`}).join('');
if(tab==='outfits')h=`<div class="section"><h3>Új szett mentése</h3><div class="outfitSave"><input id="outfitName" maxlength="64" placeholder="Szett neve"><button id="saveOutfit">Mentés</button></div></div><div class="section"><h3>Mentett szettek</h3><div class="outfitList">${outfits.map(o=>`<div class="outfit"><span><b>${String(o.name||'Szett').replace(/[&<>"']/g,'')}</b><small>${o.updated_at?new Date(o.updated_at).toLocaleString('hu-HU'):''}</small></span><button data-wear="${o.id}">Felvétel</button><button class="danger" data-del="${o.id}">Törlés</button></div>`).join('')||'<div class="muted">Még nincs mentett szetted.</div>'}</div></div>`;
content.innerHTML=h;bind()}
function bind(){document.querySelectorAll('input[type=range]').forEach(x=>x.oninput=()=>{x.nextElementSibling.textContent=x.value;let d={kind:x.dataset.kind,id:+x.dataset.id,field:x.dataset.field,value:+x.value};post('change',d);if(d.kind==='face'){a.faceFeatures[String(d.id)]=d.value}else if(d.kind==='blend'){a.headBlend[d.field]=d.value}else if(d.kind==='hair'){a.hair[d.field]=d.value}else{let bucket=d.kind==='component'?a.components:d.kind==='prop'?a.props:a.overlays;bucket[String(d.id)]=bucket[String(d.id)]||{};bucket[String(d.id)][d.field]=d.value}});document.querySelectorAll('[data-model]').forEach(b=>b.onclick=()=>{a.model=b.dataset.model==='female'?'mp_f_freemode_01':'mp_m_f_freemode_01';post('change',{kind:'model',value:b.dataset.model});render()});let so=$('#saveOutfit');if(so)so.onclick=async()=>{let n=$('#outfitName').value.trim();if(n)await post('saveOutfit',{name:n})};document.querySelectorAll('[data-wear]').forEach(b=>b.onclick=()=>post('wearOutfit',{id:+b.dataset.wear}));document.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>post('deleteOutfit',{id:+b.dataset.del}))}
window.addEventListener('message',e=>{let m=e.data;if(m.action==='open'){a=m.data||{};limits=m.limits||{};outfits=m.outfits||[];tab='identity';app.classList.remove('hide');render()}if(m.action==='limits'){limits=m.limits||{};render()}if(m.action==='outfits'){outfits=m.outfits||[];render()}if(m.action==='appearance'){a=m.data||a;limits=m.limits||limits;render()}if(m.action==='close')app.classList.add('hide')});document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;render()});$('#save').onclick=()=>post('save');$('#cancel').onclick=()=>post('cancel');$('#left').onclick=()=>post('rotate',{delta:-15});$('#right').onclick=()=>post('rotate',{delta:15});document.addEventListener('keydown',e=>{if(e.key==='Escape')post('cancel')});
